---

version: '3.4'

services:
  gvm-postgres:
    image: "postgres"
    hostname: "postgres-gvm"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres-socket:/var/run/postgresql"
      - "postgres-data:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_PASSWORD=gvm
      - POSTGRES_DB= gvm
      - POSTGRES_PASSWORD= mypassword
      - POSTGRES_USER= gvmduser

    # command: postgres -c shared_buffers=256MB -c max_connections=200

  #gvm-redis:
  #  image: "redis"
  #  hostname: "redis"
  #  restart: always
  #  volumes:
  #    - redis-socket:/var/run/redis
  #    - /etc/localtime:/etc/localtime:ro
  #    - run-redis:/run/redis
  #    - redis-data:/data
  #  command: redis-server --port 0 --unixsocket /run/redis/redis.sock --unixsocketperm 777 --databases 1025
#ulimits:
#   nofile:
#     soft: 65536
#     hard: 65536
#  gvm-openvas-scanner:
#    image: "greenbone/openvas-scanner"
#    hostname: "gvm-openvas-scanner"
#    restart: always
#    ports:
#      - "51000:51234"
#      -  443:9392
#    volumes:
#      - "redis-socket:/var/run/redis"
#      - "gvm-connect:/usr/local/var/run"
#      - "ospd-socket:/var/run/ospd"
#      - "openvas-data:/usr/local/var/lib/openvas"
#      - "gvm-data:/usr/local/var/lib/gvm"
#      - "/etc/localtime:/etc/localtime:ro"
#    depends_on:
#      - gvm-redis
    # environment:
    #   - COMMUNITY_NVT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/nvt-feed # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_SCAP_RSYNC_FEED=rsync://gvm_feed_server.service.com:/scap-data # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_GVMD_DATA_RSYNC_FEED=rsync://gvm_feed_server.service.com:/data-objects/gvmd/ # Custom feed server https://github.com/dgiorgio/gvm-feed-server
       #   - COMMUNITY_GVMD_DATA_RSYNC_FEED=rsync://gvm_feed_server.service.com:/data-objects/gvmd/ # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_CERT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/cert-data # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - ENABLE_CRON="false" # true/false - default: "true"
    #   - GVM_UPDATE_CRON=0 */3 * * * # cron config - default: 0 */12 * * *
#  gvmd:
#    image: greenbone/gvmd-gcc-build
#    hostname: gvmd
#    container_name: gvmd
#    ports:
#      - "443:9392"
#    env_file:
#      - ./config/local.env
#    volumes:
#      - ./config:/config
#      - gvm_data:/usr/local/var/lib
#      - gvm_db:/var/lib/postgresql/data
#    tty: true

  gvm:
   # image: securecompliance/gvm:latest
    image: securecompliance/gvm:debian-master-data-full
    hostname: gvm
    container_name: gvm
    ports:
      - "443:9392"
    env_file:
      - ./config/local.env
    volumes:
      - ./config:/config
      - gvm_data:/usr/local/var/lib
      - gvm_db:/var/lib/postgresql/data
    tty: true
    # environment:
    #   - COMMUNITY_NVT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/nvt-feed # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_SCAP_RSYNC_FEED=rsync://gvm_feed_server.service.com:/scap-data # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_GVMD_DATA_RSYNC_FEED=rsync://gvm_feed_server.service.com:/data-objects/gvmd/ # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - COMMUNITY_CERT_RSYNC_FEED=rsync://gvm_feed_server.service.com:/cert-data # Custom feed server https://github.com/dgiorgio/gvm-feed-server
    #   - ENABLE_CRON="false" # true/false - default: "true"
    #   - GVM_UPDATE_CRON=0 */3 * * * # cron config - default: 0 */12 * * *
    #   ### https://www.dragonflybsd.org/cgi/web-man?command=dma&section=ANY
    #   ### https://github.com/corecode/dma/blob/master/dma.conf
    #   ### https://github.com/corecode/dma/blob/master/auth.conf
    #   - SMTP_DMA_SMARTHOST=smtp.gmail.com
    #   - SMTP_DMA_PORT=587
    #   - SMTP_DMA_AUTHPATH=/etc/dma/auth.conf
    #   - SMTP_DMA_SECURETRANSFER=""
    #   - SMTP_DMA_STARTTLS=""
    #   - SMTP_DMA_MASQUERADE=example@gmail.com
    #   - SMTP_DMA_AUTH_USER=example@gmail.com
    #   - SMTP_DMA_AUTH_SMARTHOST=smtp.gmail.com
    #   - SMTP_DMA_AUTH_PASSWORD=mypassword123

  #gvm-gsa:
   # image: "greenbone/gsad"
   # hostname: "gsa"
   # restart: always
   # ports:
   #  - 8080:80
   #  - 443:9392
   # volumes:
   #   - gvm-data:/usr/local/var/lib/gvm
   #  - /etc/localtime:/etc/localtime:ro
   # links:
   #  - gvm-gvmd
   # depends_on:
   #  - gvm-gvmd
   # environment:
   #  - GVMD_ADDRESS=gvm-gvmd
   # - GVMD_PORT=9390

volumes:
  gvm-connect:
  gvm-data:
  openvas-data:
  ospd-socket:
  postgres-socket:
  postgres-data:
#  redis-socket:
#  redis-data:
#  run-redis:
  gvm_data:
    name: gvm_data
  gvm_db:
    name: gvm_db




